version: "3.8"

services:
  # Object store services.
  minio-server:
    image: minio/minio
    container_name: minio-server
    ports:
      - "9000:9000"
      - "9001:9001"
    environment:
      MINIO_ROOT_USER: minioadmin
      MINIO_ROOT_PASSWORD: minioadmin
    command: server --console-address ":9001" /data

  create-bucket:
    image: minio/mc
    container_name: create-bucket
    depends_on:
      - minio-server
    entrypoint:
      /bin/sh -c "
      /usr/bin/mc config host add modelardb-minio http://minio-server:9000 minioadmin minioadmin;
      /usr/bin/mc mb modelardb-minio/modelardb;
      exit 0;
      "

  # ModelarDB services.
  modelardb-manager:
    image: modelardb
    container_name: modelardb-manager
    command: [ "target/debug/modelardbm", "s3://modelardb" ]
    ports:
      - "9998:9998"
    environment:
      AWS_ACCESS_KEY_ID: minioadmin
      AWS_SECRET_ACCESS_KEY: minioadmin
      AWS_DEFAULT_REGION: eu-central-1
      AWS_ENDPOINT: http://minio-server:9000
      AWS_ALLOW_HTTP: "true"
    depends_on:
      - minio-server
      - create-bucket

  modelardb-edge-1:
    image: modelardb
    container_name: modelardb-edge-1
    command: [ "target/debug/modelardbd", "edge", "memory://", "grpc://modelardb-manager:9998" ]
    ports:
      - "9991:9991"
    environment:
      MODELARDBD_UNCOMPRESSED_DATA_BUFFER_CAPACITY: 640
      MODELARDBD_COMPRESSED_RESERVED_MEMORY_IN_BYTES: 10000
      MODELARDBD_TRANSFER_BATCH_SIZE_IN_BYTES: 10000
      MODELARDBD_IP_ADDRESS: host.docker.internal
      MODELARDBD_PORT: 9991
      AWS_DEFAULT_REGION: eu-central-1
      AWS_ALLOW_HTTP: "true"
    restart: on-failure:10
    depends_on:
      - modelardb-manager

  modelardb-edge-2:
    image: modelardb
    container_name: modelardb-edge-2
    command: [ "target/debug/modelardbd", "edge", "memory://", "grpc://modelardb-manager:9998" ]
    ports:
      - "9992:9992"
    environment:
      MODELARDBD_UNCOMPRESSED_DATA_BUFFER_CAPACITY: 640
      MODELARDBD_COMPRESSED_RESERVED_MEMORY_IN_BYTES: 10000
      MODELARDBD_TRANSFER_BATCH_SIZE_IN_BYTES: 10000
      MODELARDBD_IP_ADDRESS: host.docker.internal
      MODELARDBD_PORT: 9992
      AWS_DEFAULT_REGION: eu-central-1
      AWS_ALLOW_HTTP: "true"
    restart: on-failure:10
    depends_on:
      - modelardb-manager

  modelardb-edge-3:
    image: modelardb
    container_name: modelardb-edge-3
    command: [ "target/debug/modelardbd", "edge", "memory://", "grpc://modelardb-manager:9998" ]
    ports:
      - "9993:9993"
    environment:
      MODELARDBD_UNCOMPRESSED_DATA_BUFFER_CAPACITY: 640
      MODELARDBD_COMPRESSED_RESERVED_MEMORY_IN_BYTES: 10000
      MODELARDBD_TRANSFER_BATCH_SIZE_IN_BYTES: 10000
      MODELARDBD_IP_ADDRESS: host.docker.internal
      MODELARDBD_PORT: 9993
      AWS_DEFAULT_REGION: eu-central-1
      AWS_ALLOW_HTTP: "true"
    restart: on-failure:10
    depends_on:
      - modelardb-manager

  modelardb-edge-4:
    image: modelardb
    container_name: modelardb-edge-4
    command: [ "target/debug/modelardbd", "edge", "memory://", "grpc://modelardb-manager:9998" ]
    ports:
      - "9994:9994"
    environment:
      MODELARDBD_UNCOMPRESSED_DATA_BUFFER_CAPACITY: 640
      MODELARDBD_COMPRESSED_RESERVED_MEMORY_IN_BYTES: 10000
      MODELARDBD_TRANSFER_BATCH_SIZE_IN_BYTES: 10000
      MODELARDBD_IP_ADDRESS: host.docker.internal
      MODELARDBD_PORT: 9994
      AWS_DEFAULT_REGION: eu-central-1
      AWS_ALLOW_HTTP: "true"
    restart: on-failure:10
    depends_on:
      - modelardb-manager

  modelardb-edge-5:
    image: modelardb
    container_name: modelardb-edge-5
    command: [ "target/debug/modelardbd", "edge", "memory://", "grpc://modelardb-manager:9998" ]
    ports:
      - "9995:9995"
    environment:
      MODELARDBD_UNCOMPRESSED_DATA_BUFFER_CAPACITY: 640
      MODELARDBD_COMPRESSED_RESERVED_MEMORY_IN_BYTES: 10000
      MODELARDBD_TRANSFER_BATCH_SIZE_IN_BYTES: 10000
      MODELARDBD_IP_ADDRESS: host.docker.internal
      MODELARDBD_PORT: 9995
      AWS_DEFAULT_REGION: eu-central-1
      AWS_ALLOW_HTTP: "true"
    restart: on-failure:10
    depends_on:
      - modelardb-manager

  modelardb-cloud-1:
    image: modelardb
    container_name: modelardb-cloud-1
    command: [ "target/debug/modelardbd", "cloud", "memory://", "grpc://modelardb-manager:9998" ]
    ports:
      - "9996:9996"
    environment:
      MODELARDBD_IP_ADDRESS: host.docker.internal
      MODELARDBD_PORT: 9996
      AWS_DEFAULT_REGION: eu-central-1
      AWS_ALLOW_HTTP: "true"
    restart: on-failure:10
    depends_on:
      - modelardb-manager

  modelardb-cloud-2:
    image: modelardb
    container_name: modelardb-cloud-2
    command: [ "target/debug/modelardbd", "cloud", "memory://", "grpc://modelardb-manager:9998" ]
    ports:
      - "9997:9997"
    environment:
      MODELARDBD_PORT: 9997
      MODELARDBD_IP_ADDRESS: host.docker.internal
      AWS_DEFAULT_REGION: eu-central-1
      AWS_ALLOW_HTTP: "true"
    restart: on-failure:10
    depends_on:
      - modelardb-manager
