version: "3.8"

services:
  # Object store services.
  minio-server:
    image: minio/minio
    container_name: minio-server
    ports:
      - "9000:9000"
      - "9001:9001"
    environment:
      MINIO_ROOT_USER: minioadmin
      MINIO_ROOT_PASSWORD: minioadmin
    command: server --console-address ":9001" /data

  create-bucket:
    image: minio/mc
    container_name: create-bucket
    depends_on:
      - minio-server
    entrypoint:
      /bin/sh -c "
      /usr/bin/mc config host add modelardb-minio http://minio-server:9000 minioadmin minioadmin;
      /usr/bin/mc mb modelardb-minio/modelardb;
      exit 0;
      "

  # ModelarDB services.
  modelardb-manager:
    image: modelardb
    container_name: modelardb-manager
    command: [ "target/debug/modelardbm", "s3://modelardb" ]
    ports:
      - "9998:9998"
    environment:
      AWS_ACCESS_KEY_ID: minioadmin
      AWS_SECRET_ACCESS_KEY: minioadmin
      AWS_DEFAULT_REGION: eu-central-1
      AWS_ENDPOINT: http://minio-server:9000
      AWS_ALLOW_HTTP: "true"
    depends_on:
      - minio-server
      - create-bucket
    healthcheck:
      test: [ "CMD", "echo", "ready" ]
      interval: 5s

  modelardb-edge-1:
    image: modelardb
    container_name: modelardb-edge-1
    command: [ "target/debug/modelardbd", "edge", "memory://", "grpc://modelardb-manager:9998" ]
    ports:
      - "9981:9981"
    environment:
      MODELARDBD_UNCOMPRESSED_DATA_BUFFER_CAPACITY: 1280
      MODELARDBD_COMPRESSED_RESERVED_MEMORY_IN_BYTES: 10000
      MODELARDBD_TRANSFER_TIME_IN_SECONDS: 10
      MODELARDBD_IP_ADDRESS: host.docker.internal
      MODELARDBD_PORT: 9981
      AWS_DEFAULT_REGION: eu-central-1
      AWS_ALLOW_HTTP: "true"
    restart: on-failure:10
    depends_on:
      modelardb-manager:
        condition: service_healthy

  modelardb-edge-2:
    image: modelardb
    container_name: modelardb-edge-2
    command: [ "target/debug/modelardbd", "edge", "memory://", "grpc://modelardb-manager:9998" ]
    ports:
      - "9982:9982"
    environment:
      MODELARDBD_UNCOMPRESSED_DATA_BUFFER_CAPACITY: 1280
      MODELARDBD_COMPRESSED_RESERVED_MEMORY_IN_BYTES: 10000
      MODELARDBD_TRANSFER_TIME_IN_SECONDS: 10
      MODELARDBD_IP_ADDRESS: host.docker.internal
      MODELARDBD_PORT: 9982
      AWS_DEFAULT_REGION: eu-central-1
      AWS_ALLOW_HTTP: "true"
    restart: on-failure:10
    depends_on:
      modelardb-manager:
        condition: service_healthy

  modelardb-edge-3:
    image: modelardb
    container_name: modelardb-edge-3
    command: [ "target/debug/modelardbd", "edge", "memory://", "grpc://modelardb-manager:9998" ]
    ports:
      - "9983:9983"
    environment:
      MODELARDBD_UNCOMPRESSED_DATA_BUFFER_CAPACITY: 1280
      MODELARDBD_COMPRESSED_RESERVED_MEMORY_IN_BYTES: 10000
      MODELARDBD_TRANSFER_TIME_IN_SECONDS: 10
      MODELARDBD_IP_ADDRESS: host.docker.internal
      MODELARDBD_PORT: 9983
      AWS_DEFAULT_REGION: eu-central-1
      AWS_ALLOW_HTTP: "true"
    restart: on-failure:10
    depends_on:
      modelardb-manager:
        condition: service_healthy

  modelardb-edge-4:
    image: modelardb
    container_name: modelardb-edge-4
    command: [ "target/debug/modelardbd", "edge", "memory://", "grpc://modelardb-manager:9998" ]
    ports:
      - "9984:9984"
    environment:
      MODELARDBD_UNCOMPRESSED_DATA_BUFFER_CAPACITY: 1280
      MODELARDBD_COMPRESSED_RESERVED_MEMORY_IN_BYTES: 10000
      MODELARDBD_TRANSFER_TIME_IN_SECONDS: 10
      MODELARDBD_IP_ADDRESS: host.docker.internal
      MODELARDBD_PORT: 9984
      AWS_DEFAULT_REGION: eu-central-1
      AWS_ALLOW_HTTP: "true"
    restart: on-failure:10
    depends_on:
      modelardb-manager:
        condition: service_healthy

  modelardb-edge-5:
    image: modelardb
    container_name: modelardb-edge-5
    command: [ "target/debug/modelardbd", "edge", "memory://", "grpc://modelardb-manager:9998" ]
    ports:
      - "9985:9985"
    environment:
      MODELARDBD_UNCOMPRESSED_DATA_BUFFER_CAPACITY: 1280
      MODELARDBD_COMPRESSED_RESERVED_MEMORY_IN_BYTES: 10000
      MODELARDBD_TRANSFER_TIME_IN_SECONDS: 10
      MODELARDBD_IP_ADDRESS: host.docker.internal
      MODELARDBD_PORT: 9985
      AWS_DEFAULT_REGION: eu-central-1
      AWS_ALLOW_HTTP: "true"
    restart: on-failure:10
    depends_on:
      modelardb-manager:
        condition: service_healthy

  modelardb-edge-6:
    image: modelardb
    container_name: modelardb-edge-6
    command: [ "target/debug/modelardbd", "edge", "memory://", "grpc://modelardb-manager:9998" ]
    ports:
      - "9986:9986"
    environment:
      MODELARDBD_UNCOMPRESSED_DATA_BUFFER_CAPACITY: 1280
      MODELARDBD_COMPRESSED_RESERVED_MEMORY_IN_BYTES: 10000
      MODELARDBD_TRANSFER_TIME_IN_SECONDS: 10
      MODELARDBD_IP_ADDRESS: host.docker.internal
      MODELARDBD_PORT: 9986
      AWS_DEFAULT_REGION: eu-central-1
      AWS_ALLOW_HTTP: "true"
    restart: on-failure:10
    depends_on:
      modelardb-manager:
        condition: service_healthy

  modelardb-edge-7:
    image: modelardb
    container_name: modelardb-edge-7
    command: [ "target/debug/modelardbd", "edge", "memory://", "grpc://modelardb-manager:9998" ]
    ports:
      - "9987:9987"
    environment:
      MODELARDBD_UNCOMPRESSED_DATA_BUFFER_CAPACITY: 1280
      MODELARDBD_COMPRESSED_RESERVED_MEMORY_IN_BYTES: 10000
      MODELARDBD_TRANSFER_TIME_IN_SECONDS: 10
      MODELARDBD_IP_ADDRESS: host.docker.internal
      MODELARDBD_PORT: 9987
      AWS_DEFAULT_REGION: eu-central-1
      AWS_ALLOW_HTTP: "true"
    restart: on-failure:10
    depends_on:
      modelardb-manager:
        condition: service_healthy

  modelardb-edge-8:
    image: modelardb
    container_name: modelardb-edge-8
    command: [ "target/debug/modelardbd", "edge", "memory://", "grpc://modelardb-manager:9998" ]
    ports:
      - "9988:9988"
    environment:
      MODELARDBD_UNCOMPRESSED_DATA_BUFFER_CAPACITY: 1280
      MODELARDBD_COMPRESSED_RESERVED_MEMORY_IN_BYTES: 10000
      MODELARDBD_TRANSFER_TIME_IN_SECONDS: 10
      MODELARDBD_IP_ADDRESS: host.docker.internal
      MODELARDBD_PORT: 9988
      AWS_DEFAULT_REGION: eu-central-1
      AWS_ALLOW_HTTP: "true"
    restart: on-failure:10
    depends_on:
      modelardb-manager:
        condition: service_healthy

  modelardb-edge-9:
    image: modelardb
    container_name: modelardb-edge-9
    command: [ "target/debug/modelardbd", "edge", "memory://", "grpc://modelardb-manager:9998" ]
    ports:
      - "9989:9989"
    environment:
      MODELARDBD_UNCOMPRESSED_DATA_BUFFER_CAPACITY: 1280
      MODELARDBD_COMPRESSED_RESERVED_MEMORY_IN_BYTES: 10000
      MODELARDBD_TRANSFER_TIME_IN_SECONDS: 10
      MODELARDBD_IP_ADDRESS: host.docker.internal
      MODELARDBD_PORT: 9989
      AWS_DEFAULT_REGION: eu-central-1
      AWS_ALLOW_HTTP: "true"
    restart: on-failure:10
    depends_on:
      modelardb-manager:
        condition: service_healthy

  modelardb-edge-10:
    image: modelardb
    container_name: modelardb-edge-10
    command: [ "target/debug/modelardbd", "edge", "memory://", "grpc://modelardb-manager:9998" ]
    ports:
      - "9990:9990"
    environment:
      MODELARDBD_UNCOMPRESSED_DATA_BUFFER_CAPACITY: 1280
      MODELARDBD_COMPRESSED_RESERVED_MEMORY_IN_BYTES: 10000
      MODELARDBD_TRANSFER_TIME_IN_SECONDS: 10
      MODELARDBD_IP_ADDRESS: host.docker.internal
      MODELARDBD_PORT: 9990
      AWS_DEFAULT_REGION: eu-central-1
      AWS_ALLOW_HTTP: "true"
    restart: on-failure:10
    depends_on:
      modelardb-manager:
        condition: service_healthy

  modelardb-cloud:
    image: modelardb
    container_name: modelardb-cloud
    command: [ "target/debug/modelardbd", "cloud", "memory://", "grpc://modelardb-manager:9998" ]
    ports:
      - "9999:9999"
    environment:
      MODELARDBD_IP_ADDRESS: host.docker.internal
      MODELARDBD_PORT: 9999
      AWS_DEFAULT_REGION: eu-central-1
      AWS_ALLOW_HTTP: "true"
    restart: on-failure:10
    depends_on:
      modelardb-manager:
        condition: service_healthy
