version: "3.8"

x-modelardb-variables: &modelardb-variables
  MODELARDBD_UNCOMPRESSED_DATA_BUFFER_CAPACITY: 1280
  MODELARDBD_COMPRESSED_RESERVED_MEMORY_IN_BYTES: 10000
  MODELARDBD_TRANSFER_TIME_IN_SECONDS: 10
  MODELARDBD_IP_ADDRESS: host.docker.internal
  AWS_DEFAULT_REGION: eu-central-1
  AWS_ALLOW_HTTP: "true"

services:
  # Object store services.
  minio-server:
    image: minio/minio
    container_name: minio-server
    ports:
      - "9000:9000"
      - "9001:9001"
    environment:
      MINIO_ROOT_USER: minioadmin
      MINIO_ROOT_PASSWORD: minioadmin
    command: server --console-address ":9001" /data

  create-bucket:
    image: minio/mc
    container_name: create-bucket
    depends_on:
      - minio-server
    entrypoint:
      /bin/sh -c "
      /usr/bin/mc config host add modelardb-minio http://minio-server:9000 minioadmin minioadmin;
      /usr/bin/mc mb modelardb-minio/modelardb;
      exit 0;
      "

  # ModelarDB services.
  modelardb-manager:
    image: modelardb
    container_name: modelardb-manager
    command: [ "target/debug/modelardbm", "s3://modelardb" ]
    ports:
      - "9998:9998"
    environment:
      AWS_ACCESS_KEY_ID: minioadmin
      AWS_SECRET_ACCESS_KEY: minioadmin
      AWS_DEFAULT_REGION: eu-central-1
      AWS_ENDPOINT: http://minio-server:9000
      AWS_ALLOW_HTTP: "true"
    depends_on:
      - minio-server
      - create-bucket
    healthcheck:
      test: [ "CMD", "echo", "ready" ]
      interval: 2s

  modelardb-edge-1: &modelardb-base
    image: modelardb
    container_name: modelardb-edge-1
    command: [ "target/debug/modelardbd", "edge", "memory://", "grpc://modelardb-manager:9998" ]
    ports:
      - "9981:9981"
    environment:
      <<: *modelardb-variables
      MODELARDBD_PORT: 9981
    restart: on-failure:10
    depends_on:
      modelardb-manager:
        condition: service_healthy
    healthcheck:
      test: [ "CMD", "echo", "ready" ]
      interval: 1s

  modelardb-edge-2:
    <<: *modelardb-base
    container_name: modelardb-edge-2
    ports:
      - "9982:9982"
    environment:
      <<: *modelardb-variables
      MODELARDBD_PORT: 9982
    depends_on:
      modelardb-edge-1:
        condition: service_healthy

  modelardb-edge-3:
    <<: *modelardb-base
    container_name: modelardb-edge-3
    ports:
      - "9983:9983"
    environment:
      <<: *modelardb-variables
      MODELARDBD_PORT: 9983
    depends_on:
      modelardb-edge-2:
        condition: service_healthy

  modelardb-edge-4:
    <<: *modelardb-base
    container_name: modelardb-edge-4
    ports:
      - "9984:9984"
    environment:
      <<: *modelardb-variables
      MODELARDBD_PORT: 9984
    depends_on:
      modelardb-edge-3:
        condition: service_healthy

  modelardb-edge-5:
    <<: *modelardb-base
    container_name: modelardb-edge-5
    ports:
      - "9985:9985"
    environment:
      <<: *modelardb-variables
      MODELARDBD_PORT: 9985
    depends_on:
      modelardb-edge-4:
        condition: service_healthy

  modelardb-edge-6:
    <<: *modelardb-base
    container_name: modelardb-edge-6
    ports:
      - "9986:9986"
    environment:
      <<: *modelardb-variables
      MODELARDBD_PORT: 9986
    depends_on:
      modelardb-edge-5:
        condition: service_healthy

  modelardb-edge-7:
    <<: *modelardb-base
    container_name: modelardb-edge-7
    ports:
      - "9987:9987"
    environment:
      <<: *modelardb-variables
      MODELARDBD_PORT: 9987
    depends_on:
      modelardb-edge-6:
        condition: service_healthy

  modelardb-edge-8:
    <<: *modelardb-base
    container_name: modelardb-edge-8
    ports:
      - "9988:9988"
    environment:
      <<: *modelardb-variables
      MODELARDBD_PORT: 9988
    depends_on:
      modelardb-edge-7:
        condition: service_healthy

  modelardb-edge-9:
    <<: *modelardb-base
    container_name: modelardb-edge-9
    ports:
      - "9989:9989"
    environment:
      <<: *modelardb-variables
      MODELARDBD_PORT: 9989
    depends_on:
      modelardb-edge-8:
        condition: service_healthy

  modelardb-edge-10:
    <<: *modelardb-base
    container_name: modelardb-edge-10
    ports:
      - "9990:9990"
    environment:
      <<: *modelardb-variables
      MODELARDBD_PORT: 9990
    depends_on:
      modelardb-edge-9:
        condition: service_healthy

  modelardb-cloud:
    <<: *modelardb-base
    container_name: modelardb-cloud
    command: [ "target/debug/modelardbd", "cloud", "memory://", "grpc://modelardb-manager:9998" ]
    ports:
      - "9999:9999"
    environment:
      <<: *modelardb-variables
      MODELARDBD_PORT: 9999
    depends_on:
      modelardb-edge-10:
        condition: service_healthy
