version: "3.8"

x-aws-variables: &aws-variables
  AWS_ACCESS_KEY_ID: minioadmin
  AWS_SECRET_ACCESS_KEY: minioadmin
  AWS_DEFAULT_REGION: eu-central-1
  AWS_ENDPOINT: http://minio-server:9000
  AWS_ALLOW_HTTP: "true"

x-modelardb-variables: &modelardb-variables
  MODELARDBD_IP_ADDRESS: host.docker.internal
  AWS_DEFAULT_REGION: eu-central-1
  AWS_ALLOW_HTTP: "true"

services:
  # Object store services.
  minio-server:
    image: minio/minio
    container_name: minio-server
    ports:
      - "9000:9000"
      - "9001:9001"
    environment:
      MINIO_ROOT_USER: minioadmin
      MINIO_ROOT_PASSWORD: minioadmin
    command: server --console-address ":9001" /data

  create-bucket:
    image: minio/mc
    container_name: create-bucket
    depends_on:
      - minio-server
    entrypoint:
      /bin/sh -c "
      /usr/bin/mc config host add modelardb-minio http://minio-server:9000 minioadmin minioadmin;
      /usr/bin/mc mb modelardb-minio/modelardb;
      /usr/bin/mc mb modelardb-minio/parquet;
      exit 0;
      "

  # ModelarDB services.
  modelardb-manager:
    image: modelardb
    container_name: modelardb-manager
    command: [ "target/release/modelardbm", "s3://modelardb" ]
    ports:
      - "9980:9980"
    environment:
      <<: *aws-variables
      MODELARDBM_PORT: 9980
    depends_on:
      - minio-server
      - create-bucket
    healthcheck:
      test: [ "CMD", "echo", "ready" ]
      interval: 2s

  modelardb-edge-1: &modelardb-base
    image: modelardb
    container_name: modelardb-edge-1
    command: [ "target/release/modelardbd", "edge", "memory://", "grpc://modelardb-manager:9980" ]
    ports:
      - "9981:9981"
    environment:
      <<: *modelardb-variables
      MODELARDBD_PORT: 9981
    restart: on-failure:10
    depends_on:
      modelardb-manager:
        condition: service_healthy
    healthcheck:
      test: [ "CMD", "echo", "ready" ]
      interval: 1s

  modelardb-edge-2:
    <<: *modelardb-base
    container_name: modelardb-edge-2
    ports:
      - "9982:9982"
    environment:
      <<: *modelardb-variables
      MODELARDBD_PORT: 9982
    depends_on:
      modelardb-edge-1:
        condition: service_healthy

  modelardb-edge-3:
    <<: *modelardb-base
    container_name: modelardb-edge-3
    ports:
      - "9983:9983"
    environment:
      <<: *modelardb-variables
      MODELARDBD_PORT: 9983
    depends_on:
      modelardb-edge-2:
        condition: service_healthy

  modelardb-edge-4:
    <<: *modelardb-base
    container_name: modelardb-edge-4
    ports:
      - "9984:9984"
    environment:
      <<: *modelardb-variables
      MODELARDBD_PORT: 9984
    depends_on:
      modelardb-edge-3:
        condition: service_healthy

  modelardb-edge-5:
    <<: *modelardb-base
    container_name: modelardb-edge-5
    ports:
      - "9985:9985"
    environment:
      <<: *modelardb-variables
      MODELARDBD_PORT: 9985
    depends_on:
      modelardb-edge-4:
        condition: service_healthy

  modelardb-edge-6:
    <<: *modelardb-base
    container_name: modelardb-edge-6
    ports:
      - "9986:9986"
    environment:
      <<: *modelardb-variables
      MODELARDBD_PORT: 9986
    depends_on:
      modelardb-edge-5:
        condition: service_healthy

  modelardb-edge-7:
    <<: *modelardb-base
    container_name: modelardb-edge-7
    ports:
      - "9987:9987"
    environment:
      <<: *modelardb-variables
      MODELARDBD_PORT: 9987
    depends_on:
      modelardb-edge-6:
        condition: service_healthy

  modelardb-edge-8:
    <<: *modelardb-base
    container_name: modelardb-edge-8
    ports:
      - "9988:9988"
    environment:
      <<: *modelardb-variables
      MODELARDBD_PORT: 9988
    depends_on:
      modelardb-edge-7:
        condition: service_healthy

  modelardb-edge-9:
    <<: *modelardb-base
    container_name: modelardb-edge-9
    ports:
      - "9989:9989"
    environment:
      <<: *modelardb-variables
      MODELARDBD_PORT: 9989
    depends_on:
      modelardb-edge-8:
        condition: service_healthy

  modelardb-edge-10:
    <<: *modelardb-base
    container_name: modelardb-edge-10
    ports:
      - "9990:9990"
    environment:
      <<: *modelardb-variables
      MODELARDBD_PORT: 9990
    depends_on:
      modelardb-edge-9:
        condition: service_healthy

  modelardb-edge-11:
    <<: *modelardb-base
    container_name: modelardb-edge-11
    ports:
      - "9991:9991"
    environment:
      <<: *modelardb-variables
      MODELARDBD_PORT: 9991
    depends_on:
      modelardb-edge-10:
        condition: service_healthy

  modelardb-edge-12:
    <<: *modelardb-base
    container_name: modelardb-edge-12
    ports:
      - "9992:9992"
    environment:
      <<: *modelardb-variables
      MODELARDBD_PORT: 9992
    depends_on:
      modelardb-edge-11:
        condition: service_healthy

  modelardb-cloud:
    <<: *modelardb-base
    container_name: modelardb-cloud
    command: [ "target/release/modelardbd", "cloud", "memory://", "grpc://modelardb-manager:9980" ]
    ports:
      - "9999:9999"
    environment:
      <<: *modelardb-variables
      MODELARDBD_PORT: 9999
    depends_on:
      modelardb-edge-12:
        condition: service_healthy

  # Simple Parquet services.
  parquet-manager:
    image: modelardb
    container_name: parquet-manager
    command: [ "target/release/modelardbm", "s3://parquet" ]
    ports:
      - "9880:9880"
    environment:
      <<: *aws-variables
      MODELARDBM_PORT: 9880
    depends_on:
      - minio-server
      - create-bucket
    healthcheck:
      test: [ "CMD", "echo", "ready" ]
      interval: 2s

  parquet-edge-1: &parquet-base
    image: modelardb
    container_name: parquet-edge-1
    command: [ "target/release/modelardbd", "edge", "memory://", "grpc://parquet-manager:9880" ]
    ports:
      - "9881:9881"
    environment:
      <<: *modelardb-variables
      MODELARDBD_PORT: 9881
    restart: on-failure:10
    depends_on:
      parquet-manager:
        condition: service_healthy
    healthcheck:
      test: [ "CMD", "echo", "ready" ]
      interval: 1s

  parquet-edge-2:
    <<: *parquet-base
    container_name: parquet-edge-2
    ports:
      - "9882:9882"
    environment:
      <<: *modelardb-variables
      MODELARDBD_PORT: 9882
    depends_on:
      parquet-edge-1:
        condition: service_healthy

  parquet-edge-3:
    <<: *parquet-base
    container_name: parquet-edge-3
    ports:
      - "9883:9883"
    environment:
      <<: *modelardb-variables
      MODELARDBD_PORT: 9883
    depends_on:
      parquet-edge-2:
        condition: service_healthy

  parquet-edge-4:
    <<: *parquet-base
    container_name: parquet-edge-4
    ports:
      - "9884:9884"
    environment:
      <<: *modelardb-variables
      MODELARDBD_PORT: 9884
    depends_on:
      parquet-edge-3:
        condition: service_healthy

  parquet-edge-5:
    <<: *parquet-base
    container_name: parquet-edge-5
    ports:
      - "9885:9885"
    environment:
      <<: *modelardb-variables
      MODELARDBD_PORT: 9885
    depends_on:
      parquet-edge-4:
        condition: service_healthy

  parquet-edge-6:
    <<: *parquet-base
    container_name: parquet-edge-6
    ports:
      - "9886:9886"
    environment:
      <<: *modelardb-variables
      MODELARDBD_PORT: 9886
    depends_on:
      parquet-edge-5:
        condition: service_healthy

  parquet-edge-7:
    <<: *parquet-base
    container_name: parquet-edge-7
    ports:
      - "9887:9887"
    environment:
      <<: *modelardb-variables
      MODELARDBD_PORT: 9887
    depends_on:
      parquet-edge-6:
        condition: service_healthy

  parquet-edge-8:
    <<: *parquet-base
    container_name: parquet-edge-8
    ports:
      - "9888:9888"
    environment:
      <<: *modelardb-variables
      MODELARDBD_PORT: 9888
    depends_on:
      parquet-edge-7:
        condition: service_healthy

  parquet-edge-9:
    <<: *parquet-base
    container_name: parquet-edge-9
    ports:
      - "9889:9889"
    environment:
      <<: *modelardb-variables
      MODELARDBD_PORT: 9889
    depends_on:
      parquet-edge-8:
        condition: service_healthy

  parquet-edge-10:
    <<: *parquet-base
    container_name: parquet-edge-10
    ports:
      - "9890:9890"
    environment:
      <<: *modelardb-variables
      MODELARDBD_PORT: 9890
    depends_on:
      parquet-edge-9:
        condition: service_healthy

  parquet-edge-11:
    <<: *parquet-base
    container_name: parquet-edge-11
    ports:
      - "9891:9891"
    environment:
      <<: *modelardb-variables
      MODELARDBD_PORT: 9891
    depends_on:
      parquet-edge-10:
        condition: service_healthy

  parquet-edge-12:
    <<: *parquet-base
    container_name: parquet-edge-12
    ports:
      - "9892:9892"
    environment:
      <<: *modelardb-variables
      MODELARDBD_PORT: 9892
    depends_on:
      parquet-edge-11:
        condition: service_healthy

  parquet-cloud:
    <<: *parquet-base
    container_name: parquet-cloud
    command: [ "target/release/modelardbd", "cloud", "memory://", "grpc://parquet-manager:9880" ]
    ports:
      - "9899:9899"
    environment:
      <<: *modelardb-variables
      MODELARDBD_PORT: 9899
    depends_on:
      parquet-edge-12:
        condition: service_healthy
