x-aws-variables: &aws-variables
  AWS_ACCESS_KEY_ID: minioadmin
  AWS_SECRET_ACCESS_KEY: minioadmin
  AWS_DEFAULT_REGION: eu-central-1
  AWS_ENDPOINT: http://minio-server:9000
  AWS_ALLOW_HTTP: true

x-modelardb-variables: &modelardb-variables
  MODELARDBD_IP_ADDRESS: host.docker.internal
  MODELARDBD_RETENTION_PERIOD_IN_SECONDS: 0
  AWS_DEFAULT_REGION: eu-central-1
  AWS_ALLOW_HTTP: true

services:
  # Object store services.
  minio-server:
    image: minio/minio
    container_name: minio-server
    ports:
      - "9000:9000"
      - "9001:9001"
    environment:
      MINIO_ROOT_USER: minioadmin
      MINIO_ROOT_PASSWORD: minioadmin
    command: server --console-address ":9001" /data

  create-bucket:
    image: minio/mc
    container_name: create-bucket
    depends_on:
      - minio-server
    entrypoint:
      /bin/sh -c "
      sleep 2;
      /usr/bin/mc alias set modelardb-minio http://minio-server:9000 minioadmin minioadmin;
      /usr/bin/mc mb modelardb-minio/modelardb;
      /usr/bin/mc mb modelardb-minio/parquet;
      /usr/bin/mc mb modelardb-minio/comparison;
      exit 0;
      "

  # ModelarDB services.
  modelardb-manager:
    image: cgodiksen/modelardb
    container_name: modelardb-manager
    command: [ "target/release/modelardbm", "s3://modelardb" ]
    ports:
      - "9980:9980"
    environment:
      <<: *aws-variables
      MODELARDBM_PORT: 9980
    depends_on:
      create-bucket:
        condition: service_completed_successfully
    healthcheck:
      test: [ "CMD", "echo", "ready" ]
      interval: 2s

  modelardb-edge-1: &modelardb-base
    image: cgodiksen/modelardb
    container_name: modelardb-edge-1
    command: [ "target/release/modelardbd", "edge", "data/edge", "grpc://modelardb-manager:9980" ]
    ports:
      - "9981:9981"
    environment:
      <<: *modelardb-variables
      MODELARDBD_PORT: 9981
    volumes:
      - modelardb-9981:/usr/src/app/data/edge
    restart: on-failure:10
    depends_on:
      modelardb-manager:
        condition: service_healthy
    healthcheck:
      test: [ "CMD", "echo", "ready" ]
      interval: 1s

  modelardb-edge-2:
    <<: *modelardb-base
    container_name: modelardb-edge-2
    ports:
      - "9982:9982"
    environment:
      <<: *modelardb-variables
      MODELARDBD_PORT: 9982
    volumes:
      - modelardb-9982:/usr/src/app/data/edge
    depends_on:
      modelardb-edge-1:
        condition: service_healthy

  modelardb-edge-3:
    <<: *modelardb-base
    container_name: modelardb-edge-3
    ports:
      - "9983:9983"
    environment:
      <<: *modelardb-variables
      MODELARDBD_PORT: 9983
    volumes:
      - modelardb-9983:/usr/src/app/data/edge
    depends_on:
      modelardb-edge-2:
        condition: service_healthy

  modelardb-edge-4:
    <<: *modelardb-base
    container_name: modelardb-edge-4
    ports:
      - "9984:9984"
    environment:
      <<: *modelardb-variables
      MODELARDBD_PORT: 9984
    volumes:
      - modelardb-9984:/usr/src/app/data/edge
    depends_on:
      modelardb-edge-3:
        condition: service_healthy

  modelardb-cloud:
    <<: *modelardb-base
    container_name: modelardb-cloud
    command: [ "target/release/modelardbd", "cloud", "data/cloud", "grpc://modelardb-manager:9980" ]
    ports:
      - "9999:9999"
    environment:
      <<: *modelardb-variables
      MODELARDBD_PORT: 9999
    depends_on:
      modelardb-edge-4:
        condition: service_healthy

  # Simple Parquet services.
  parquet-manager:
    image: cgodiksen/modelardb
    container_name: parquet-manager
    command: [ "target/release/modelardbm", "s3://parquet" ]
    ports:
      - "9880:9880"
    environment:
      <<: *aws-variables
      MODELARDBM_PORT: 9880
    depends_on:
      create-bucket:
        condition: service_completed_successfully
    healthcheck:
      test: [ "CMD", "echo", "ready" ]
      interval: 2s

  parquet-edge-1: &parquet-base
    image: cgodiksen/modelardb
    container_name: parquet-edge-1
    command: [ "target/release/modelardbd", "edge", "data/edge", "grpc://parquet-manager:9880" ]
    ports:
      - "9881:9881"
    environment:
      <<: *modelardb-variables
      MODELARDBD_PORT: 9881
    volumes:
      - comparison-9881:/usr/src/app/data/edge
    restart: on-failure:10
    depends_on:
      parquet-manager:
        condition: service_healthy
    healthcheck:
      test: [ "CMD", "echo", "ready" ]
      interval: 1s

  parquet-edge-2:
    <<: *parquet-base
    container_name: parquet-edge-2
    ports:
      - "9882:9882"
    environment:
      <<: *modelardb-variables
      MODELARDBD_PORT: 9882
    volumes:
      - comparison-9882:/usr/src/app/data/edge
    depends_on:
      parquet-edge-1:
        condition: service_healthy

  parquet-edge-3:
    <<: *parquet-base
    container_name: parquet-edge-3
    ports:
      - "9883:9883"
    environment:
      <<: *modelardb-variables
      MODELARDBD_PORT: 9883
    volumes:
      - comparison-9883:/usr/src/app/data/edge
    depends_on:
      parquet-edge-2:
        condition: service_healthy

  parquet-edge-4:
    <<: *parquet-base
    container_name: parquet-edge-4
    ports:
      - "9884:9884"
    environment:
      <<: *modelardb-variables
      MODELARDBD_PORT: 9884
    volumes:
      - comparison-9884:/usr/src/app/data/edge
    depends_on:
      parquet-edge-3:
        condition: service_healthy

  parquet-cloud:
    <<: *parquet-base
    container_name: parquet-cloud
    command: [ "target/release/modelardbd", "cloud", "data/cloud", "grpc://parquet-manager:9880" ]
    ports:
      - "9899:9899"
    environment:
      <<: *modelardb-variables
      MODELARDBD_PORT: 9899
    depends_on:
      parquet-edge-4:
        condition: service_healthy

  comparison-1:
    build: comparison-system/.
    image: comparison-system
    container_name: comparison-1
    ports:
      - "8000:8000"
    environment:
      FLIGHT_PORT: 8000
    volumes:
      - comparison-1:/usr/src/app/data

volumes:
  modelardb-9981:
  modelardb-9982:
  modelardb-9983:
  modelardb-9984:
  comparison-9881:
  comparison-9882:
  comparison-9883:
  comparison-9884:
  comparison-1:
